# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Transformer": "00_prep.ipynb",
         "getSTW": "01_dataloader.ipynb",
         "file_dir": "01_dataloader.ipynb",
         "splitData": "01_dataloader.ipynb",
         "DatasetTraj": "01_dataloader.ipynb",
         "zero_padding": "01_dataloader.ipynb",
         "Difference": "02_model.ipynb",
         "TrajectoryDN": "02_model.ipynb",
         "TrajectorySN": "02_model.ipynb",
         "ContrastiveLoss": "02_model.ipynb",
         "contastive_loss": "02_model.ipynb",
         "device": "03_train.ipynb",
         "BATCH_SIZE": "03_train.ipynb",
         "EPOCHS": "03_train.ipynb",
         "mode": "03_train.ipynb",
         "run_name": "03_train.ipynb",
         "get_data_and_model": "03_train.ipynb",
         "get_prf": "03_train.ipynb",
         "get_metric": "03_train.ipynb",
         "write_metric": "03_train.ipynb",
         "train": "03_train.ipynb",
         "test": "03_train.ipynb",
         "train_DN": "03_train.ipynb",
         "train_SN": "03_train.ipynb"}

modules = ["prep.py",
           "dataloader.py",
           "model.py",
           "train.py"]

doc_url = "https://pages.github.FKTechLab.com./DifferenceNet/ti/"

git_url = "https://github.com/FKTechLab/DifferenceNet/tree/main/"

def custom_doc_links(name): return None
