# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_prep.ipynb (unless otherwise specified).

__all__ = ['Transformer']

# Cell
import pandas as pd

# Cell
class Transformer:
    '''Transform raw data to get derived features'''
    def __init__(self):
        self.features_traj = [
            'lat', 'lng', 'sine_time', 'cose_time'
        ]
        self.features_org = [
            'org_lat', 'org_lng', 'org_sine_time', 'org_cose_time'
        ]

    def transform(self, X):
        '''Break down X into x1 and x2'''
        x1 = X[self.features_traj].values
        # x1[:, 0] = x1[:, 0]/90.0
        # x1[:, 1] = x1[:, 1]/180.0
        x1 = x1.tolist()

        x2_org = X[self.features_org].values
        # x2_org[:, 0] = x2_org[:, 0]/90.0
        # x2_org[:, 1] = x2_org[:, 1]/180.0
        x2_org = x2_org.tolist()
        return x1, x2_org